FROM oven/bun:1-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install

# Generate Prisma client
COPY prisma ./prisma
ENV DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
RUN bunx prisma generate

EXPOSE 3000
CMD ["bunx", "next", "dev", "--hostname", "0.0.0.0"]
